stages:
  - build
  - deploy

build:
  stage: build
  script:
    - gradle build
  tags:
    - 'Team #YOLOSWAG *dabs* SWS'

deploy:
  stage: deploy
  script:
    - gradle publishToWebServer
  tags:
    - 'Team #YOLOSWAG *dabs* SWS'
  only:
    - tags