package protocol;

/**
 * Created by TrottaSN on 2/1/2017.
 *
 */
public enum Keywords {
    VERSION, GET, POST, PUT, HEAD, DELETE, HOST, CONNECTION, USER_AGENT, SERVER_INFO, PROVIDER, AUTHOR, CLOSE, OPEN,
    DEFAULT_FILE, MIME_TEXT, DATE, SERVER, LAST_MODIFIED, CONTENT_LENGTH, CONTENT_TYPE, SPACE, SEPARATOR, SLASH, CR, LF,
    OK, MOVED_PERMANENTLY, NOT_MODIFIED, BAD_REQUEST, NOT_FOUND, INTERNAL_SERVER_ERROR, NOT_IMPLEMENTED,
    HTTP_VERSION_NOT_SUPPORTED
}